version: "3.8"
services:
    db:
        image: mysql:8
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=dogdid
            - MYSQL_USER=dogdid
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - ./.dbvolume:/var/lib/mysql
            - ./.dev_db_init:/docker-entrypoint-initdb.d
volumes:
    dbdata6:
